<a href="https://colab.research.google.com/github/Cevestawalker/Evolution/blob/main/Day2_Lists_Tuples_Sets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# ================== LISTS ==================
fruits = ["apple", "banana", "cherry", "mango"]
print(fruits)
print(type(fruits))
print(len(fruits))

# Access, Modify, Add, Remove
print(fruits[0])          # apple
fruits[1] = "blueberry"   # change
fruits.append("orange")   # add at end
fruits.insert(0, "grape") # add at position
fruits.remove("cherry")   # remove by value
popped = fruits.pop()     # remove last
print(fruits)

['apple', 'banana', 'cherry', 'mango']
<class 'list'>
4
apple
['grape', 'apple', 'blueberry', 'mango']


In [ ]:
# Slicing & Useful Methods
numbers = [10, 20, 30, 40, 50, 60]
print(numbers[1:4])       # [20, 30, 40]
print(numbers[:3])        # first 3
print(numbers[-2:])       # last 2

numbers.sort()            # permanent sort
numbers.reverse()
print(50 in numbers)      # True

[20, 30, 40]
[10, 20, 30]
[50, 60]
True


In [ ]:
# ================== TUPLES ==================
# Immutable (cannot change) → super fast
colors = ("red", "green", "blue")
print(colors[1])
# colors[0] = "yellow"    # ← This will give error!

# Tuple unpacking (very useful in ML)
x, y, z = colors
print(x, y, z)

green
red green blue


In [ ]:
# ================== SETS ==================
# No duplicates, no order, super fast search
unique = {1, 2, 2, 3, 3, 3}
print(unique)             # {1, 2, 3}

a = {1, 2, 3}
b = {3, 4, 5}
print(a.union(b))         # {1,2,3,4,5}
print(a.intersection(b))  # {3}
print(a.difference(b))    # {1,2}

{1, 2, 3}
{1, 2, 3, 4, 5}
{3}
{1, 2}


In [ ]:
#Exercise create a list of 5 movies
movies = ["Commando", "Rambo", "Mortal Kombat", "Reacher", "Peaky blinder"]

#print the third movie
print(movies[2])

Mortal Kombat


In [ ]:
#Add one more movie to list
movies.append("Expendables")
print(movies)

['Commando', 'Rambo', 'Mortal Kombat', 'Reacher', 'Peaky blinder', 'Expendables']


In [ ]:
#Remove the first movie
movies.pop(0)
print(movies)

['Rambo', 'Mortal Kombat', 'Reacher', 'Peaky blinder', 'Expendables']


In [ ]:
#Tuples
coordinates = (10.5, 20.8)

print(coordinates[0])
print(coordinates[1])


10.5
20.8


In [ ]:
#sets of numbers
numbers = {1, 2, 2, 3, 4, 4, 5}

print(len(numbers))

5


In [ ]:
#list input and sum and average
nums = []
for i in range(5):
    nums.append(int(input("Enter number: ")))
print("Sum =", sum(nums))
print("Average =", sum(nums)/len(nums))

Enter number: 1


KeyboardInterrupt: Interrupted by user

In [ ]:
#Sort list
scores = [45, 78, 90, 34, 67]
scores.sort()
print(scores)

In [ ]:
#slicing method
favorite_food = ["Yogurt", "Eba", "Amala", "Beans", "Rice"]
print(favorite_food[:3])

In [ ]:
#Two sets
A = {1,2,3,4}
B = {3,4,5,6}
print(A.union(B))
print(A.intersection(B))

In [ ]:
#Tuple
city = ["Lagos", "London", "Glasgow", "Dudley"]
a, b, c, d = city
print(a, b, c, d)

In [ ]:
#List
numbers = [1,2,3,4,5,6,7,8,9,10]
even = [num for num in numbers if num % 2 == 0]
print(even)

In [ ]:
#list to sets to list remove duplicates
lst = [int(x) for x in input("Enter 5 nums: ").split()]
unique_list = list(set(lst))
print(unique_list)

In [ ]:
#Student list
students = ["Alice", "Bob", "Charlie"]
students.insert(1, "David")
students.remove("Bob")

print(students)

In [ ]:
#Tuples combination
t1 = [1,2,3]
t2 = [4,5,6]

print(t1 + t2)

In [ ]:
#list of 10 random numbers

numbers = [1, 2, 2, 3, 4, 5, 6, 3, 6, 9]
unique_numbers = list(set(numbers))
print(len(unique_numbers))

7


In [ ]:
print("=== STUDENT MANAGER ===")
students = ["Alex", "Sara", "John"]

while True:
    print("\n1. Add student\n2. Remove student\n3. Show all\n4. Exit")
    choice = input("Choose: ")

    if choice == "1":
        name = input("Enter name: ")
        students.append(name)
    elif choice == "2":
        name = input("Enter name to remove: ")
        if name in students:
            students.remove(name)
    elif choice == "3":
        print(students)
    elif choice == "4":
        break

print("Final students:", students)

=== STUDENT MANAGER ===

1. Add student
2. Remove student
3. Show all
4. Exit
Choose: 1
Enter name: Funmi

1. Add student
2. Remove student
3. Show all
4. Exit
Choose: 2
Enter name to remove: Alex

1. Add student
2. Remove student
3. Show all
4. Exit
Choose: 3
['Sara', 'John', 'Funmi']

1. Add student
2. Remove student
3. Show all
4. Exit
Choose: 4
Final students: ['Sara', 'John', 'Funmi']


In [ ]:
#===============DAY THREE_dICTIONARIES_STRINGS===============

# ================== DICTIONARIES ==================
student = {
    "name": "Emma",
    "age": 20,
    "grade": "A",
    "subjects": ["Math", "Physics", "Python"],
    "active": True
}

print(student["name"])
print(student.get("age"))
print(student.keys())
print(student.values())
print(student.items())

# Modify & Add
student["age"] = 21
student["city"] = "New York"
del student["active"]

# Loop through dictionary
for key, value in student.items():
    print(key, ":", value)



In [ ]:
# ================== STRINGS ==================
text = "  Hello, Python World!  "

print(text.upper())
print(text.lower())
print(text.strip())           # remove spaces
print(text.replace("Python", "AI/ML"))

print("Python" in text)
print(text.startswith("Hello"))
print(text.endswith("!"))

# Splitting & Joining
words = text.split()          # split by space
print(words)

csv = "apple,banana,cherry"
fruits = csv.split(",")
print(fruits)

joined = " | ".join(fruits)
print(joined)

# f-strings (Best way in modern Python)
name = "Alex"
age = 21
print(f"My name is {name} and I am {age} years old.")

  HELLO, PYTHON WORLD!  
  hello, python world!  
Hello, Python World!
  Hello, AI/ML World!  
True
False
False
['Hello,', 'Python', 'World!']
['apple', 'banana', 'cherry']
apple | banana | cherry
My name is Alex and I am 21 years old.


In [ ]:
#Exercise
#dictionaries

person = {
    "name" : "Funmi",
    "age" : 30,
    "city" : "Ado"
}

print(person["name"])

Funmi


In [ ]:
#modify and add
person["hobby"] = "coding"
for key, value in person.items():
  print(key, ":", value)

name : Funmi
age : 30
city : Ado
hobby : coding


In [ ]:
#Update age
person["age"] = 25
person.pop("city", None) # Safely remove 'city' if it exists, otherwise do nothing

for key, value in person.items():
  print(key, ":", value)

name : Funmi
age : 25
hobby : coding


In [ ]:
#===========strings=========

message = "  Welcome to AI/ML  "

print(message.strip())
print(message.upper())

Welcome to AI/ML
  WELCOME TO AI/ML  


In [ ]:
#Input

fruit = input("Enter your favorite fruit: ")

print(f"You like {fruit}!")

Enter your favorite fruit: mango
You like mango!


In [ ]:
#Average score
scores = {
    "Math" : 85,
    "Science" : 92,
    "English" : 78
}
Avg_scores = sum(scores.values()) / len(scores.values())
print(f"Average score: {Avg_scores}")

Average score: 85.0


In [ ]:
#Add a new subject

scores["History"] = 88
for keys, values in scores.items():
  print(keys, ":", values)

Math : 85
Science : 92
English : 78
History : 88


In [ ]:
sentence = input("Enter a sentence: ")
words = sentence.split()
word_count = len(words)
print(f"The sentence has {word_count} words.")

Enter a sentence: Funmitan is a girl
The sentence has 4 words.


In [ ]:
students = {
    "Funmi" : 88,
    "Tope" : 72,
    "Larry" : 70
}

for keys, values in students.items():
  print(keys, ":", values)

Funmi : 88
Tope : 72
Larry : 70


In [ ]:
my_string = "This is a sample string with spaces."
new_string = my_string.replace(" ", "-")
print(new_string)

This-is-a-sample-string-with-spaces.


In [ ]:
# Define the inventory dictionary
inventory = {
    "apple": 50,
    "banana": 30,
    "orange": 40
}

# Get user input for the fruit choice
choice = input("Enter fruit: ")

# Use the .get() method to retrieve the quantity, with a default message if not found
quantity = inventory.get(choice)

# Check if a quantity was returned (meaning the fruit exists)
if quantity is not None:
    print(f"The quantity of {choice} is: {quantity}")
else:
    print(f"{choice} is not available in the inventory.")

Enter fruit: banana
The quantity of banana is: 30


In [ ]:
firstname = input("Enter first name: ")
lastname = input("Enter last name: ")
fullname = firstname + " " + lastname  # Corrected: concatenate with '+' operator and add a space
print(fullname.title())

Enter first name: rahul
Enter last name: sharma
Rahul Sharma


In [ ]:
words = {
    "motion" : "to move from one point to another",
    "tall" : "the height of a thing or object",
    "verb" : "a word used to describe an action",
    "noun" : "a word used to describe a person, place, or thing",
    "adjective" : "a word used to describe a feature"
}
print("What is a verb?")
print(words["verb"])

What is a verb?
a word used to describe an action


In [ ]:
sentence = input("Enter a sentence: ")
# Convert the sentence to lowercase to ignore case
sentence_lower = sentence.lower()

vowels = "aeiou"
count = 0
for char in sentence_lower:
  if char in vowels:
    count += 1
# Print the total count after the loop finishes
print(f"The sentence has {count} vowels.")

Enter a sentence: oluwafunmitan is a girl
The sentence has 9 vowels.


In [ ]:
d1 = {
    "a" : 1,
    "b" : 2
}

d2 = {
    "b" : 3,
    "c" : 4
}
#merge
merged_dict = {**d1, **d2}
print(merged_dict)

{'a': 1, 'b': 3, 'c': 4}


In [ ]:
print("=== STUDENT REPORT CARD ===")

student = {}

student["name"] = input("Enter student name: ")
student["roll"] = int(input("Enter roll number: "))

subjects = ["Math", "Science", "English"]
for sub in subjects:
    student[sub] = int(input(f"Enter marks in {sub}: "))

# Calculate total and percentage
total = sum([student[sub] for sub in subjects])
percentage = total / len(subjects)

student["total"] = total
student["percentage"] = round(percentage, 2)
student["grade"] = "A" if percentage >= 80 else "B" if percentage >= 60 else "C"

print("\n--- REPORT ---")
for key, value in student.items():
    print(f"{key.capitalize():10}: {value}")

=== STUDENT REPORT CARD ===
Enter student name: Walker
Enter roll number: 1411
Enter marks in Math: 76
Enter marks in Science: 88
Enter marks in English: 69

--- REPORT ---
Name      : Walker
Roll      : 1411
Math      : 76
Science   : 88
English   : 69
Total     : 233
Percentage: 77.67
Grade     : B


In [ ]:
#DAY 4_LOOPS_CONDITIONALS

# ================== CONDITIONAL STATEMENTS ==================
age = 18

if age >= 18:
    print("You are an adult")
elif age >= 13:
    print("You are a teenager")
else:
    print("You are a child")

# Multiple conditions
marks = 85
if marks >= 90:
    grade = "A+"
elif marks >= 80:
    grade = "A"
elif marks >= 70:
    grade = "B"
else:
    grade = "C"
print("Grade:", grade)

You are an adult
Grade: A


In [ ]:
# ================== LOOPS ==================

# For loop
for i in range(5):           # 0 to 4
    print(i)

for i in range(1, 6):
    print(i, end=" ")

print("\n---")

fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
    print(fruit)

# While loop
count = 0
while count < 5:
    print("Count:", count)
    count += 1

0
1
2
3
4
1 2 3 4 5 
---
apple
banana
cherry
Count: 0
Count: 1
Count: 2
Count: 3
Count: 4


In [ ]:
# Break, Continue, Pass
for i in range(10):
    if i == 5:
        break          # stop loop
    if i % 2 == 0:
        continue       # skip this iteration
    print(i)

1
3


In [ ]:
num = int(input("Enter a number: "))

if num % 2 == 0:
    print("Even")
else:
    print("Odd")

Enter a number: 44
Even


In [ ]:
#Age as input
age = int(input("Enter your age: "))

if age >= 18:
  print("Eligible to vote")
else:
  print("Not eligible")

Enter your age: 17
Not eligible


In [ ]:
#For and While loop

for i in range(1, 11):
  print(i)

count = 1
while count < 11:
  print(count)
  count += 1

1
2
3
4
5
6
7
8
9
10
1
2
3
4
5
6
7
8
9
10


In [ ]:
#multiplication table
num_to_multiply = int(input("Enter the number for the multiplication table: "))
for i in range(1, 11):
  print(f"{num_to_multiply} * {i} = {num_to_multiply * i}")

Enter the number for the multiplication table: 5
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50


In [ ]:
n = int(input("Enter a number (n): "))

# Calculate the sum of the first n natural numbers
# Using the formula: n * (n + 1) / 2
sum_n_natural = n * (n + 1) // 2

print(f"The sum of the first {n} natural numbers is: {sum_n_natural}")

Enter a number (n): 11
The sum of the first 11 natural numbers is: 66


In [ ]:
#Check number

num = int(input("Enter a number: "))

if num > 0:
  print(f" {num} is positive")
elif num < 0:
  print(f" {num} is negative")
else:
  (print(f"number is zero"))

Enter a number: 0
number is zero


Here's the code to print even numbers between 1 and 50:

In [ ]:
print("Even numbers between 1 and 50:")
even_numbers = []
for num in range(1, 51): # Loop from 1 to 50
    if num % 2 == 0: # Check if the number is even
        even_numbers.append(num)
print(even_numbers)

Even numbers between 1 and 50:
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]


In [ ]:
#string

words = "today is thursday of March"
words = words.lower()

vowels = "aeiou"
count = 0

for char in words.lower():
  if char in vowels:
    count += 1

print(f"The sentence contain {count} vowels.")

The sentence contain 7 vowels.


In [ ]:
for i in range(1, 6):
    print("*" * i)

*
**
***
****
*****


In [ ]:
for i in range(5, 0, -1):
    print("*" * i)

*****
****
***
**
*


In [ ]:
n = int(input("Enter the number of Fibonacci numbers to generate: "))

a, b = 0, 1
count = 0

if n <= 0:
    print("Please enter a positive integer.")
elif n == 1:
    print("Fibonacci sequence up to", n, ":")
    print(a)
else:
    print("Fibonacci sequence up to", n, ":")
    while count < n:
        print(a, end=" ")
        nth = a + b
        a = b
        b = nth
        count += 1
print()

Enter the number of Fibonacci numbers to generate: 4
Fibonacci sequence up to 4 :
0 1 1 2 


In [ ]:
import math

num = int(input("Enter a number: "))

# Prime numbers are natural numbers greater than 1
if num <= 1:
    is_prime = False
elif num == 2:
    is_prime = True
else:
    is_prime = True
    # Check for divisors from 2 up to the square root of num
    # We only need to check up to int(math.sqrt(num)) + 1
    # because if a number has a divisor greater than its square root,
    # it must also have a divisor smaller than its square root.
    for i in range(2, int(math.sqrt(num)) + 1):
        if num % i == 0:
            is_prime = False
            break # No need to check further, it's not prime

if is_prime:
    print(f"{num} is a Prime number")
else:
    print(f"{num} is not a Prime number")

Enter a number: 7
7 is a Prime number


In [ ]:
rows = 5

for i in range(1, rows + 1):
    # Print leading spaces
    print(" " * (rows - i), end="")
    # Print stars
    print("*" * (2 * i - 1))

    *
   ***
  *****
 *******
*********


In [ ]:
numbers = []
for i in range(5):
    while True:
        try:
            num = int(input(f"Enter number {i+1}: "))
            numbers.append(num)
            break
        except ValueError:
            print("Invalid input. Please enter an integer.")

if numbers:
    largest_number = max(numbers)
    smallest_number = min(numbers)
    print(f"The list of numbers is: {numbers}")
    print(f"The largest number is: {largest_number}")
    print(f"The smallest number is: {smallest_number}")
else:
    print("No numbers were entered.")

Enter number 1: 7
Enter number 2: 8
Enter number 3: 2
Enter number 4: 9
Enter number 5: 4
The list of numbers is: [7, 8, 2, 9, 4]
The largest number is: 9
The smallest number is: 2


In [ ]:
import random

secret_number = random.randint(1, 50) # Generate a random number between 1 and 50
attempts = 7

print("Welcome to the Number Guessing Game!")
print(f"I'm thinking of a number between 1 and 50. You have {attempts} attempts.")

for attempt_num in range(1, attempts + 1):
    try:
        guess = int(input(f"Attempt {attempt_num}/{attempts}: Enter your guess: "))

        if guess < 1 or guess > 50:
            print("Your guess is out of range (1-50). Please try again.")
            continue

        if guess < secret_number:
            print("Too low!")
        elif guess > secret_number:
            print("Too high!")
        else:
            print(f"Correct! You guessed the number {secret_number} in {attempt_num} attempts!")
            break
    except ValueError:
        print("Invalid input. Please enter a whole number.")

else:
    print(f"Sorry, you've run out of attempts! The secret number was {secret_number}.")
print("Thanks for playing!")

Welcome to the Number Guessing Game!
I'm thinking of a number between 1 and 50. You have 7 attempts.
Attempt 1/7: Enter your guess: 6
Too low!
Attempt 2/7: Enter your guess: 23
Too low!
Attempt 3/7: Enter your guess: 45
Too high!
Attempt 4/7: Enter your guess: 28
Too low!
Attempt 5/7: Enter your guess: 17
Too low!
Attempt 6/7: Enter your guess: 9
Too low!
Attempt 7/7: Enter your guess: 33
Too high!
Sorry, you've run out of attempts! The secret number was 30.
Thanks for playing!


In [ ]:
print("=== SIMPLE CALCULATOR ===")

while True:
    print("\n1. Add\n2. Subtract\n3. Multiply\n4. Divide\n5. Exit")
    choice = input("Choose operation (1-5): ")

    if choice == "5":
        print("Thank you!")
        break

    num1 = float(input("Enter first number: "))
    num2 = float(input("Enter second number: "))

    if choice == "1":
        print("Result:", num1 + num2)
    elif choice == "2":
        print("Result:", num1 - num2)
    elif choice == "3":
        print("Result:", num1 * num2)
    elif choice == "4":
        if num2 == 0:
            print("Cannot divide by zero!")
        else:
            print("Result:", num1 / num2)
    else:
        print("Invalid choice!")

=== SIMPLE CALCULATOR ===

1. Add
2. Subtract
3. Multiply
4. Divide
5. Exit
Choose operation (1-5): 3
Enter first number: 2
Enter second number: 18
Result: 36.0

1. Add
2. Subtract
3. Multiply
4. Divide
5. Exit
Choose operation (1-5): 5
Thank you!


In [ ]:
#DAY 5
# ================== BASIC FUNCTIONS ==================
def greet():
    print("Hello, Welcome to AI/ML Journey!")

greet()
greet()

Hello, Welcome to AI/ML Journey!
Hello, Welcome to AI/ML Journey!


In [ ]:
# Function with parameters
def greet_user(name):
    print(f"Hello {name}! How are you today?")

greet_user("Alex")
greet_user("Sara")

Hello Alex! How are you today?
Hello Sara! How are you today?


In [ ]:
# Function with return value
def add(a, b):
    return a + b

result = add(10, 25)
print("Sum =", result)

# Multiple returns
def calculate(a, b):
    sum_val = a + b
    diff = a - b
    prod = a * b
    return sum_val, diff, prod

s, d, p = calculate(20, 8)
print(s, d, p)

Sum = 35
28 12 160


In [ ]:
# Default arguments + Keyword arguments
def introduce(name, age=18, city="Unknown"):
    print(f"My name is {name}, I am {age} years old and I live in {city}.")

introduce("Emma")
introduce("Rahul", 22)
introduce("Priya", city="Mumbai", age=19)

My name is Emma, I am 18 years old and I live in Unknown.
My name is Rahul, I am 22 years old and I live in Unknown.
My name is Priya, I am 19 years old and I live in Mumbai.


In [ ]:
# Variable number of arguments
def total_marks(*marks):
    print("Total =", sum(marks))

total_marks(85, 92, 78, 95)

Total = 350


In [ ]:
# Lambda function (anonymous)
square = lambda x: x ** 2
print(square(7))

add_two = lambda x, y: x + y
print(add_two(5, 3))

49
8


In [ ]:
#Exercise
def say_hello():
  print("Hello, Python Learner!")

say_hello()

Hello, Python Learner!


In [ ]:
def greet(name):
  print(f"Welcome {name} to Day 5.")

greet("Samuel")

Welcome Samuel to Day 5.


In [ ]:
def square(num):
  square = num ** 2
  return square

print(square(9))

81


In [ ]:
def is_even(num):
  is_even = num % 2 == 0
  return is_even

print(is_even(9))


False


In [ ]:
def add_numbers(a, b, c=0):
  add_numbers = a + b + c
  return add_numbers

a, b, c = 10, 22, 40
result = add_numbers(a, b, c)
print(result)

72


In [ ]:
def find_max(a, b, c):
  find_max = max(a, b, c)
  return find_max

a, b, c = 40, 34, 42
print(find_max(a, b, c))

42


In [ ]:
def factorial(n):
  result = 1
  for i in range(1, n + 1):
    result *= i
  return result

print(factorial(4))


24


In [ ]:
def count_vowels(text):
  text = text.lower()
  vowels = "aeiou"
  count = 0
  for char in text:
    if char in vowels:
      count += 1
  return count

print(count_vowels("Ada is a girl"))

5


In [ ]:
def temperature_converter(temp, unit="C"):
  if unit == "C":
    fahrenheit = (temp * 9/5) + 32
    return fahrenheit

  elif unit == "F":
    celsius = (temp - 32) * 5/9
    return celsius
  else:
    return "Invalid unit. Use 'C' for Celsius or 'F' for Fahrenheit."

print(temperature_converter(60, "F"))


15.555555555555555


In [ ]:
def calculate_grade(marks):
  if marks >= 70:
    grade = "A"
  elif marks >= 60:
    grade = "B"
  elif marks >= 50:
    grade = "C"
  elif marks >= 40:
    grade = "D"
  else:
    grade = "F"
  return grade

print(calculate_grade(39))

F


In [ ]:
import math

def is_prime(n):
  if n <= 1:
    return False  # Numbers less than or equal to 1 are not prime
  elif n == 2:
    return True   # 2 is the only even prime number
  elif n % 2 == 0:
    return False  # Other even numbers are not prime
  else:
    # Check for divisors from 3 up to the square root of n (only odd numbers)
    for i in range(3, int(math.sqrt(n)) + 1, 2):
      if n % i == 0:
        return False
    return True

print(f"Is 7 prime? {is_prime(7)}")      # Expected: True
print(f"Is 10 prime? {is_prime(10)}")     # Expected: False
print(f"Is 1 prime? {is_prime(1)}")       # Expected: False
print(f"Is 2 prime? {is_prime(2)}")       # Expected: True
print(f"Is 29 prime? {is_prime(29)}")     # Expected: True
print(f"Is 9 prime? {is_prime(9)}")      # Expected: False

Is 7 prime? True
Is 10 prime? False
Is 1 prime? False
Is 2 prime? True
Is 29 prime? True
Is 9 prime? False


In [ ]:
def fibonacci(n):
    a, b = 0, 1
    count = 0

    if n <= 0:
        print("Please enter a positive integer.")
    elif n == 1:
        print("Fibonacci sequence:")
        print(a)
    else:
        print("Fibonacci sequence:")
        while count < n:
            print(a, end=" ")
            nth = a + b
            a = b
            b = nth
            count += 1
        print()

print("--- Test Cases ---")
fibonacci(7)
fibonacci(1)
fibonacci(0)
fibonacci(10)

--- Test Cases ---
Fibonacci sequence:
0 1 1 2 3 5 8 
Fibonacci sequence:
0
Please enter a positive integer.
Fibonacci sequence:
0 1 1 2 3 5 8 13 21 34 


In [ ]:
def stats(numbers):
    if not numbers:
        return {"error": "List is empty, cannot calculate statistics"}

    total_sum = sum(numbers)
    count = len(numbers)
    average = total_sum / count
    maximum = max(numbers)
    minimum = min(numbers)

    return {
        "sum": total_sum,
        "average": average,
        "max": maximum,
        "min": minimum
    }

# Test cases
list1 = [10, 20, 30, 40, 50]
print(f"Stats for {list1}: {stats(list1)}")

list2 = [5, 1, 9, 3, 7]
print(f"Stats for {list2}: {stats(list2)}")

empty_list = []
print(f"Stats for {empty_list}: {stats(empty_list)}")

Stats for [10, 20, 30, 40, 50]: {'sum': 150, 'average': 30.0, 'max': 50, 'min': 10}
Stats for [5, 1, 9, 3, 7]: {'sum': 25, 'average': 5.0, 'max': 9, 'min': 1}
Stats for []: {'error': 'List is empty, cannot calculate statistics'}


In [ ]:
def calculator(num1, num2, operation):
    if operation == "+":
        return num1 + num2
    elif operation == "-":
        return num1 - num2
    elif operation == "*":
        return num1 * num2
    elif operation == "/":
        if num2 == 0:
            return "Error: Cannot divide by zero!"
        return num1 / num2
    else:
        return "Error: Invalid operation. Please use '+', '-', '*', or '/'."

# Example usage:
print(f"10 + 5 = {calculator(10, 5, '+')}")
print(f"10 - 5 = {calculator(10, 5, '-')}")
print(f"10 * 5 = {calculator(10, 5, '*')}")
print(f"10 / 5 = {calculator(10, 5, '/')}")
print(f"10 / 0 = {calculator(10, 0, '/')}")
print(f"10 ^ 5 = {calculator(10, 5, '^')}")

In [ ]:
def generate_pattern(rows, symbol="*"):
    for i in range(1, rows+1):
        print(symbol * i)

generate_pattern(5)

*
**
***
****
*****


In [ ]:
def add(x, y):    return x + y
def subtract(x, y): return x - y
def multiply(x, y): return x * y
def divide(x, y):
    if y == 0: return "Cannot divide by zero!"
    return x / y

def calculator():
    print("=== Smart Calculator ===")
    while True:
        print("\n1. Add\n2. Subtract\n3. Multiply\n4. Divide\n5. Exit")
        choice = input("Choose (1-5): ")

        if choice == "5":
            print("Goodbye!")
            break

        num1 = float(input("Enter first number: "))
        num2 = float(input("Enter second number: "))

        if choice == "1":
            print("Result =", add(num1, num2))
        elif choice == "2":
            print("Result =", subtract(num1, num2))
        elif choice == "3":
            print("Result =", multiply(num1, num2))
        elif choice == "4":
            print("Result =", divide(num1, num2))
        else:
            print("Invalid choice!")

calculator()

=== Smart Calculator ===

1. Add
2. Subtract
3. Multiply
4. Divide
5. Exit
Choose (1-5): 3
Enter first number: 23
Enter second number: 2
Result = 46.0

1. Add
2. Subtract
3. Multiply
4. Divide
5. Exit
Choose (1-5): 1
Enter first number: 33
Enter second number: 54
Result = 87.0

1. Add
2. Subtract
3. Multiply
4. Divide
5. Exit
Choose (1-5): 5
Goodbye!


In [ ]:
#Day 6 File Handling in Python
# ================== WRITING TO FILES ==================
# 'w' = write (overwrites if file exists)
with open("my_first_file.txt", "w") as file:
    file.write("Hello from Day 6!\n")
    file.write("This is my first file in Python.\n")
    file.write("Learning file handling for AI/ML.\n")

print("File written successfully!")

File written successfully!


In [ ]:
# ================== APPEND MODE ==================
with open("my_first_file.txt", "a") as file:
    file.write("This line is appended on Day 6.\n")

# Reading again to see changes
with open("my_first_file.txt", "r") as file:
    print(file.read())

Hello from Day 6!
This is my first file in Python.
Learning file handling for AI/ML.
This line is appended on Day 6.



In [ ]:
# ================== APPEND MODE ==================
with open("my_first_file.txt", "a") as file:
    file.write("This line is appended on Day 6.\n")

# Reading again to see changes
with open("my_first_file.txt", "r") as file:
    print(file.read())

Hello from Day 6!
This is my first file in Python.
Learning file handling for AI/ML.
This line is appended on Day 6.
This line is appended on Day 6.



In [ ]:
# ================== Working with CSV files (Very Important for ML) ==================
import csv

# Writing CSV
data = [
    ["Name", "Age", "City", "Score"],
    ["Alex", 21, "New York", 85],
    ["Sara", 19, "London", 92],
    ["Rahul", 23, "Mumbai", 78]
]

with open("students.csv", "w", newline="") as file:
    writer = csv.writer(file)
    writer.writerows(data)

print("CSV file created!")

CSV file created!


In [ ]:
# Reading CSV
with open("students.csv", "r") as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)

['Name', 'Age', 'City', 'Score']
['Alex', '21', 'New York', '85']
['Sara', '19', 'London', '92']
['Rahul', '23', 'Mumbai', '78']


In [ ]:
#create a file
with open("greeting.txt", "w") as file:
  file.write("Welcome to Day 6 File Handling!\n")
  file.write("Hello, i am your new neighbor.\n")

print("file written successfully")

#to read
with open("greeting.txt", "r") as file:
  print(file.read())

file written successfully
Welcome to Day 6 File Handling!
Hello, i am your new neighbor.



In [ ]:
#write mode
with open("info.txt", "w") as file:
  file.write("My name is Samuel.\n")
  file.write("Today is March 27.\n")

print("file written successfully")

#to read
with open("info.txt", "r") as file:
  print(file.read())


file written successfully
My name is Samuel.
Today is March 27.



In [ ]:
#to append
with open("info.txt", "a") as file:
  file.write("Hello, I am your neighbor\n")
  file.write("I am learning file handling\n")
  file.write("I am a graduate of the University of Toronto\n")

#Reading the Info
with open("info.txt", "r") as file:
  print(file.read())

My name is Samuel.
Today is March 27.
Hello, I am your neighbor
I am learning file handling
I am a graduate of the University of Toronto
Hello, I am your neighbor
I am learning file handling
I am a graduate of the University of Toronto
Hello, I am your neighbor
I am learning file handling
I am a graduate of the University of Toronto



In [ ]:
#create a file number
with open("numbers.txt", "w") as file:
  file.write("1\n")
  file.write("2\n")
  file.write("3\n")
  file.write("4\n")
  file.write("5\n")
  file.write("6\n")
  file.write("7\n")
  file.write("8\n")
  file.write("9\n")
  file.write("10\n")
  file.write("11\n")
  file.write("12\n")
  file.write("13\n")
  file.write("14\n")
  file.write("15\n")
  file.write("16\n")
  file.write("17\n")
  file.write("18\n")
  file.write("19\n")
  file.write("20\n")

print("file written successfully")

file written successfully


In [ ]:
with open("numbers.txt", "r") as file:
  numbers = file.readlines()
  current_sum = 0
  for number in numbers:
    current_sum += int(number)
print("The sum of numbers in numbers.txt is:", current_sum)

The sum of numbers in numbers.txt is: 210


In [ ]:
with open("even_odd.txt", "w") as file:
    for i in range(1, 51):
        if i % 2 == 0:
            file.write(f"Even: {i}\n")
        else:
            file.write(f"Odd: {i}\n")

print("File 'even_odd.txt' created successfully!")

# Read and print the content of the file to verify
with open("even_odd.txt", "r") as file:
    print("\nContent of even_odd.txt:")
    print(file.read())

File 'even_odd.txt' created successfully!

Content of even_odd.txt:
Odd: 1
Even: 2
Odd: 3
Even: 4
Odd: 5
Even: 6
Odd: 7
Even: 8
Odd: 9
Even: 10
Odd: 11
Even: 12
Odd: 13
Even: 14
Odd: 15
Even: 16
Odd: 17
Even: 18
Odd: 19
Even: 20
Odd: 21
Even: 22
Odd: 23
Even: 24
Odd: 25
Even: 26
Odd: 27
Even: 28
Odd: 29
Even: 30
Odd: 31
Even: 32
Odd: 33
Even: 34
Odd: 35
Even: 36
Odd: 37
Even: 38
Odd: 39
Even: 40
Odd: 41
Even: 42
Odd: 43
Even: 44
Odd: 45
Even: 46
Odd: 47
Even: 48
Odd: 49
Even: 50



In [ ]:
print("Enter 5 student names:")
students = []
for i in range(5):
    name = input(f"Student {i+1}: ")
    students.append(name)

with open("students.txt", "w") as file:
    for student_name in students:
        file.write(student_name + "\n")

print("File 'students.txt' created successfully with the entered names!")

# Read and print the content of the file to verify
with open("students.txt", "r") as file:
    print("\nContent of students.txt:")
    print(file.read())

Enter 5 student names:
Student 1: Funmi
Student 2: Sam
Student 3: Lola
Student 4: Tunji
Student 5: Jame
File 'students.txt' created successfully with the entered names!

Content of students.txt:
Funmi
Sam
Lola
Tunji
Jame



In [ ]:
import datetime

# Get the current date and time
current_time = datetime.datetime.now()

# Format the message
log_message = f"Day 6 completed at {current_time.strftime('%Y-%m-%d %H:%M:%S')}"

# Open activity.log in append mode and write the message
with open("activity.log", "a") as file:
    file.write(log_message + "\n")

print(f"Log message appended to activity.log: '{log_message}'")

# Read and print the content of the file to verify
with open("activity.log", "r") as file:
    print("\nContent of activity.log:")
    print(file.read())

Log message appended to activity.log: 'Day 6 completed at 2026-03-29 07:47:25'

Content of activity.log:
Day 6 completed at 2026-03-29 07:47:25



In [ ]:
import csv

# Define the headers and some sample data for 5 students
headers = ["Name", "Math", "Science", "English"]
students_marks = [
    ["Alice", 85, 90, 78],
    ["Bob", 72, 65, 80],
    ["Charlie", 95, 88, 92],
    ["David", 60, 70, 75],
    ["Eve", 88, 92, 85]
]

file_name = "marks.csv"

# Write the data to the CSV file
with open(file_name, "w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(headers) # Write the header row
    writer.writerows(students_marks) # Write the student data rows

print(f"File '{file_name}' created successfully with student marks!")

# Read and print the content of the file to verify
print(f"\nContent of {file_name}:")
with open(file_name, "r") as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)

File 'marks.csv' created successfully with student marks!

Content of marks.csv:
['Name', 'Math', 'Science', 'English']
['Alice', '85', '90', '78']
['Bob', '72', '65', '80']
['Charlie', '95', '88', '92']
['David', '60', '70', '75']
['Eve', '88', '92', '85']


In [1]:
import csv

def save_data(filename, data):
    """
    Saves a list of lists as a CSV file.

    Args:
        filename (str): The name of the CSV file to create.
        data (list of list): A list of lists representing the data to save.
                             Each inner list is a row in the CSV.
    """
    try:
        with open(filename, 'w', newline='') as file:
            writer = csv.writer(file)
            writer.writerows(data)
        print(f"Data successfully saved to '{filename}'.")
    except IOError as e:
        print(f"Error saving data to file: {e}")

# Example usage:
example_data = [
    ["Name", "Age", "City"],
    ["Alice", 30, "New York"],
    ["Bob", 24, "London"],
    ["Charlie", 35, "Paris"]
]

save_data("example.csv", example_data)

# You can also verify the content by reading it back
print("\nVerifying content of example.csv:")
with open("example.csv", "r") as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)


Data successfully saved to 'example.csv'.

Verifying content of example.csv:
['Name', 'Age', 'City']
['Alice', '30', 'New York']
['Bob', '24', 'London']
['Charlie', '35', 'Paris']


In [2]:
#Function that reads CSV and returns list of dict
import csv

def read_csv_as_dict(filename):
    """
    Reads a CSV file and returns its content as a list of dictionaries.
    Each dictionary represents a row, with column headers as keys.

    Args:
        filename (str): The name of the CSV file to read.

    Returns:
        list: A list of dictionaries, where each dictionary is a row.
              Returns an empty list if the file is not found or empty.
    """
    data_list = []
    try:
        with open(filename, 'r', newline='') as file:
            reader = csv.DictReader(file)
            for row in reader:
                data_list.append(row)
        print(f"Data successfully read from '{filename}'.")
        return data_list
    except FileNotFoundError:
        print(f"Error: File '{filename}' not found.")
        return []
    except Exception as e:
        print(f"An error occurred: {e}")
        return []

# Example usage with the previously created 'example.csv':
data_from_csv = read_csv_as_dict("example.csv")

if data_from_csv:
    print("\nContent as list of dictionaries:")
    for row_dict in data_from_csv:
        print(row_dict)


Data successfully read from 'example.csv'.

Content as list of dictionaries:
{'Name': 'Alice', 'Age': '30', 'City': 'New York'}
{'Name': 'Bob', 'Age': '24', 'City': 'London'}
{'Name': 'Charlie', 'Age': '35', 'City': 'Paris'}


In [3]:
def add_task(task_description):
    """Appends a new task to the todo.txt file."""
    with open("todo.txt", "a") as file:
        file.write(task_description + "\n")
    print(f"Task '{task_description}' added.")

def view_tasks():
    """Reads and prints all tasks from the todo.txt file."""
    try:
        with open("todo.txt", "r") as file:
            tasks = file.readlines()
        if not tasks:
            print("Your todo list is empty!")
        else:
            print("\n--- Your Todo List ---")
            for i, task in enumerate(tasks, 1):
                print(f"{i}. {task.strip()}")
            print("----------------------")
    except FileNotFoundError:
        print("No todo list found. Start by adding a task!")

def todo_manager():
    """Main function to manage the todo list."""
    print("=== Todo List Manager ===")
    while True:
        print("\n1. Add Task\n2. View Tasks\n3. Exit")
        choice = input("Enter your choice: ")

        if choice == '1':
            task = input("Enter the task description: ")
            add_task(task)
        elif choice == '2':
            view_tasks()
        elif choice == '3':
            print("Exiting Todo List Manager. Goodbye!")
            break
        else:
            print("Invalid choice. Please try again.")

# Run the todo manager
todo_manager()


=== Todo List Manager ===

1. Add Task
2. View Tasks
3. Exit
Enter your choice: 1
Enter the task description: surveys
Task 'surveys' added.

1. Add Task
2. View Tasks
3. Exit
Enter your choice: 3
Exiting Todo List Manager. Goodbye!


In [4]:
#Personal Diary/journal App
import datetime

def write_diary():
    date = datetime.date.today()
    print(f"\nWriting diary for {date}")
    entry = input("How was your day? Write your thoughts:\n")

    with open("my_diary.txt", "a") as file:
        file.write(f"\n{'='*50}\n")
        file.write(f"Date: {date}\n")
        file.write(f"Entry:\n{entry}\n")
        file.write(f"{'='*50}\n")
    print("Entry saved successfully! 📖")

def read_diary():
    try:
        with open("my_diary.txt", "r") as file:
            print(file.read())
    except FileNotFoundError:
        print("No diary entries yet. Start writing!")

while True:
    print("\n=== PERSONAL DIARY ===")
    print("1. Write new entry")
    print("2. Read all entries")
    print("3. Exit")
    choice = input("Choose (1-3): ")

    if choice == "1":
        write_diary()
    elif choice == "2":
        read_diary()
    elif choice == "3":
        print("See you tomorrow! Keep learning AI/ML 💪")
        break
    else:
        print("Invalid choice!")


=== PERSONAL DIARY ===
1. Write new entry
2. Read all entries
3. Exit
Choose (1-3): 2
No diary entries yet. Start writing!

=== PERSONAL DIARY ===
1. Write new entry
2. Read all entries
3. Exit
Choose (1-3): 1

Writing diary for 2026-03-31
How was your day? Write your thoughts:
Today is my graduation
Entry saved successfully! 📖

=== PERSONAL DIARY ===
1. Write new entry
2. Read all entries
3. Exit
Choose (1-3): 1

Writing diary for 2026-03-31
How was your day? Write your thoughts:
i am in a state of ectasy and today is going as planned
Entry saved successfully! 📖

=== PERSONAL DIARY ===
1. Write new entry
2. Read all entries
3. Exit
Choose (1-3): 2

Date: 2026-03-31
Entry:
Today is my graduation

Date: 2026-03-31
Entry:
i am in a state of ectasy and today is going as planned


=== PERSONAL DIARY ===
1. Write new entry
2. Read all entries
3. Exit
Choose (1-3): 3
See you tomorrow! Keep learning AI/ML 💪


In [5]:
#Day 7 Object-oriented Programming (OOP) in python
# ================== CLASS & OBJECT ==================
class Person:
    def __init__(self, name, age):   # Constructor
        self.name = name             # Instance attributes
        self.age = age

    def introduce(self):             # Method
        print(f"Hi, I'm {self.name} and I'm {self.age} years old.")

    def have_birthday(self):
        self.age += 1
        print(f"Happy Birthday {self.name}! Now you are {self.age}.")

# Creating objects
p1 = Person("Alex", 21)
p2 = Person("Sara", 19)

p1.introduce()
p2.introduce()
p1.have_birthday()

Hi, I'm Alex and I'm 21 years old.
Hi, I'm Sara and I'm 19 years old.
Happy Birthday Alex! Now you are 22.


In [6]:
# ================== INHERITANCE ==================
class Student(Person):               # Student inherits from Person
    def __init__(self, name, age, grade, subjects):
        super().__init__(name, age)  # Call parent constructor
        self.grade = grade
        self.subjects = subjects

    def study(self):
        print(f"{self.name} is studying {self.subjects}")

class Teacher(Person):
    def __init__(self, name, age, subject, salary):
        super().__init__(name, age)
        self.subject = subject
        self.salary = salary

    def teach(self):
        print(f"{self.name} is teaching {self.subject}")

# Using inheritance
s1 = Student("Emma", 20, "A", ["Math", "Python"])
t1 = Teacher("Mr. Sharma", 45, "AI", 75000)

s1.introduce()
s1.study()
t1.introduce()
t1.teach()

Hi, I'm Emma and I'm 20 years old.
Emma is studying ['Math', 'Python']
Hi, I'm Mr. Sharma and I'm 45 years old.
Mr. Sharma is teaching AI


In [7]:
# ================== ENCAPSULATION (Private attributes) ==================
class BankAccount:
    def __init__(self, owner, balance=0):
        self.owner = owner
        self.__balance = balance   # private (name mangling)

    def deposit(self, amount):
        if amount > 0:
            self.__balance += amount
            print(f"Deposited {amount}. New balance: {self.__balance}")

    def get_balance(self):
        return self.__balance

acc = BankAccount("Alex", 5000)
acc.deposit(2000)
print(acc.get_balance())
# print(acc.__balance)   # This will raise error

Deposited 2000. New balance: 7000
7000


In [14]:
#Day7 Exercise 1 create class with Attributes and methods

class Dog():
  def __init__(self, name, age):
    self.name = name
    self.age = age
#method
  def bark(self):
    print(f"{self.name} says Woof!")

In [13]:
#exercise 2: create and object of dog and call bark

#create the object
d1 = Dog("McQueen", 2)
d2 = Dog("Jaqueen", 3)

d1.bark()
d2.bark()

McQueen says Woof!
Jaqueen says Woof!


In [18]:
#Exercise 3: create class Car with attributes and method
class Car():
  def __init__(self, brand, model, year):
    self.brand = brand
    self.model = model
    self.year = year

  def info(self):
     print(f"The {self.brand} {self.model} was made in {self.year}")

#create objects
c1 = Car("Mercedez", "C300", 2012)
c2 = Car("Toyota", "Corolla", 2023)

c1.info()
c2.info()

The Mercedez C300 was made in 2012
The Toyota Corolla was made in 2023


In [21]:
#Exercise 4: Add a method for age of car

def age_of_car(self, current_year):
  current_year = 2026
  age = current_year - self.year
  print(f"age of car is {age}")

age_of_car(c1, 2012)
age_of_car(c2, 2023)

age of car is 14
age of car is 3


In [23]:
#Exercise 5: Class rectangle with attributes and method
class Rectangle():
  def __init__(self, length, width):
    self.length = length
    self.width = width
#method
  def area(self, length, width):
    area = length * width
    print(f"The area of rectangle is {area}")

  def perimeter(self, length, width):
    perimeter = 2 * (length + width)
    print(f"The perimeter of rectangle is {perimeter}")


#create object
l = Rectangle(10, 5)

l.area(10, 5)
l.perimeter(10, 5)


The area of rectangle is 50
The perimeter of rectangle is 30


In [1]:
#Exercise 6: create class Employee and add method
class Employee():
  def __init__(self, name, salary, department):
    self.name = name
    self.salary = salary
    self.department = department

  def give_raise(self, percent):
    self.salary += self.salary * (percent / 100)
    print(f"The new salary of {self.name} in the {self.department} department is {self.salary}")

#create object
s1 = Employee("Rooney", 50000, "IT")
s2 = Employee("Kobbie", 60000, "HR")

s1.give_raise(10)
s2.give_raise(13)

The new salary of Rooney in the IT department is 55000.0
The new salary of Kobbie in the HR department is 67800.0


In [4]:
#Exercise 7: Inheritance
class Manager(Employee):
  def __init__(self, name, salary, department, team_size):
    super().__init__(name, salary, department)
    self.team_size = team_size

  def team_info(self):
    print(f"{self.name} is the manager of {self.department} department with a team size of {self.team_size}")

#create object
m1 = Manager("Mr. walker", 70000, "IT", 10)
m2 = Manager("Mr. Ajayi", 49000, "HR", 5)

m1.team_info()
m2.team_info()

Mr. walker is the manager of IT department with a team size of 10
Mr. Ajayi is the manager of HR department with a team size of 5


In [5]:
#Exercise 8: class circle and area method
class Circle():
  def __init__(self, radius):
    self.radius = radius

  def area(self):
    area = 3.14 * (self.radius ** 2)
    print(f"The area of circle is {area}")

#create object
c1 = Circle(5)
c2 = Circle(10)

c1.area()
c2.area()

The area of circle is 78.5
The area of circle is 314.0


In [7]:
#Exercise 9: creating a class of book
class Book():
  def __init__(self, title, author, pages):
    self.title = title
    self.author = author
    self.pages = pages

  def summary(self):
    print(f"{self.title} is a {self.pages} pages book written by {self.author}.")

#create object
b1 = Book("Atomic habits", "James Clear", 246)

b1.summary()


Atomic habits is a 246 pages book written by James Clear.


In [8]:
#Exercise 10: add class variable and increment everytime there is a new book
class Book():
  total_books = 0  # Class variable

  def __init__(self, title, author, pages):
    self.title = title
    self.author = author
    self.pages = pages
    Book.total_books += 1 # Increment class variable

# Create some book objects to test
b1 = Book("The Hobbit", "J.R.R. Tolkien", 360)
b2 = Book("1984", "George Orwell", 389)
b3 = Book("Pride and Prejudice", "Jane Austen", 299)

print(f"Total number of books created: {Book.total_books}")


Total number of books created: 3


In [13]:
#Exercise 11: class account with a withdraw method and balance check
class BankAccount():
  def __init__(self, owner, initial_balance=0):
    self.owner = owner
    self.__balance = initial_balance # Make balance private

  def deposit(self, amount):
    if amount > 0:
      self.__balance += amount
      print(f"Deposited ${amount:.2f}. New balance: ${self.__balance:.2f}")
    else:
      print("Deposit amount must be positive.")

  def withdraw(self, amount):
    if amount > 0:
      if self.__balance >= amount:
        self.__balance -= amount
        print(f"Withdrew ${amount:.2f}. New balance: ${self.__balance:.2f}")
      else:
        print(f"Insufficient balance. Current balance: ${self.__balance:.2f}. Attempted withdrawal: ${amount:.2f}")
    else:
      print("Withdrawal amount must be positive.")

  def get_balance(self):
    return self.__balance

# Create an object and test the methods
my_account = BankAccount("Alice", 1000)
print(f"Initial balance for {my_account.owner}: ${my_account.get_balance():.2f}")

my_account.deposit(500)
my_account.withdraw(200)
my_account.withdraw(1500) # This should fail
my_account.deposit(200)
my_account.withdraw(1500) # This should now pass
print(f"Final balance for {my_account.owner}: ${my_account.get_balance():.2f}")


Initial balance for Alice: $1000.00
Deposited $500.00. New balance: $1500.00
Withdrew $200.00. New balance: $1300.00
Insufficient balance. Current balance: $1300.00. Attempted withdrawal: $1500.00
Deposited $200.00. New balance: $1500.00
Withdrew $1500.00. New balance: $0.00
Final balance for Alice: $0.00


In [20]:
#Exercise 12; student mark, average and pass status
class Student:
  def __init__(self, name, subject1, subject2, subject3):
    self.name = name
    self.subject1 = subject1
    self.subject2 = subject2
    self.subject3 = subject3

  def calculate_average(self):
    return (self.subject1 + self.subject2 + self.subject3) / 3

  def is_pass(self):
    average = self.calculate_average()
    if average >= 40:
      return True
    else:
      return False

#create object
s1 = Student("Samuel", 66, 49, 87)
s2 = Student("Funmi", 34, 44, 67)
s3 = Student("Temitope", 55, 48, 73)

print(f"The average score of {s1.name} is {s1.calculate_average():.2f}. Pass status: {s1.is_pass()}")
print(f"The average score of {s2.name} is {s2.calculate_average():.2f}. Pass status: {s2.is_pass()}")
print(f"The average score of {s3.name} is {s3.calculate_average():.2f}. Pass status: {s3.is_pass()}")

The average score of Samuel is 67.33. Pass status: True
The average score of Funmi is 48.33. Pass status: True
The average score of Temitope is 58.67. Pass status: True


In [26]:
#Exercise 13: Inheritance from student
class ScienceStudent(Student):
  def __init__(self, name, subject1, subject2, subject3):
    super().__init__(name, subject1, subject2, subject3)

  def calculate_average(self):
    return (self.subject1 + self.subject2 + self.subject3) / 3

  def is_pass(self):
    average = self.calculate_average()
    if average >= 60:
      return True
    else:
      return False

class ArtsStudent(Student):
  def __init__(self, name, subject1, subject2, subject3):
    super().__init__(name, subject1, subject2, subject3)

  def calculate_average(self):
    return (self.subject1 + self.subject2 + self.subject3) / 3

  def is_pass(self):
    average = self.calculate_average()
    if average >= 50:
      return True
    else:
      return False

#create object
s1 = ScienceStudent("Samuel", 66, 49, 87)
s2 = ArtsStudent("Funmi", 34, 44, 67)

print(f"{s1.name} has an average score of {s1.calculate_average():.2f}. Pass status: {s1.is_pass()}")
print(f"{s2.name} has an average score of {s2.calculate_average():.2f}. Pass status: {s2.is_pass()}")

Samuel has an average score of 67.33. Pass status: True
Funmi has an average score of 48.33. Pass status: False


In [1]:
#Exercise 14: create a class vector
class Vector():
  def __init__(self, x, y):
    self.x = x
    self.y = y

  def __add__(self, other):       #method
    return Vector(self.x + other.x, self.y + other.y)

  def __str__(self): # Add a __str__ method for better printing
    return f"Vector({self.x}, {self.y})"

#create objects
v1 = Vector(2, 3)
v2 = Vector(4, 5)

# Add the vectors
v3 = v1 + v2

# Print the result
print(f"Vector 1: {v1}")
print(f"Vector 2: {v2}")
print(f"Sum of vectors: {v3}")

Vector 1: Vector(2, 3)
Vector 2: Vector(4, 5)
Sum of vectors: Vector(6, 8)


In [4]:
#Exercise 15: create class library and add books as object
class Library:
  def __init__(self, name):
    self.name = name
    self.books = []  # Initialize an instance variable for books

  def add_book(self, book):
    self.books.append(book)
    print(f"'{book}' has been added to {self.name}.")

  def display_books(self):
    if not self.books:
      print(f"{self.name} is currently empty.")
    else:
      print(f"\nBooks in {self.name}:")
      for i, book in enumerate(self.books, 1):
        print(f"{i}. {book}")

# Create objects
l1 = Library("My Library")
l2 = Library("Your Library")

l1.add_book("The Great Gatsby")
l1.add_book("1984")

l2.add_book("To Kill a Mockingbird")
l2.add_book("Brave New World")

l1.display_books()
l2.display_books()


'The Great Gatsby' has been added to My Library.
'1984' has been added to My Library.
'To Kill a Mockingbird' has been added to Your Library.
'Brave New World' has been added to Your Library.

Books in My Library:
1. The Great Gatsby
2. 1984

Books in Your Library:
1. To Kill a Mockingbird
2. Brave New World


In [5]:
#Mini project: student and Employee management system
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def introduce(self):
        print(f"Hi, I'm {self.name}, {self.age} years old.")

class Student(Person):
    def __init__(self, name, age, roll_no, marks):
        super().__init__(name, age)
        self.roll_no = roll_no
        self.marks = marks  # dictionary of subjects

    def get_average(self):
        return sum(self.marks.values()) / len(self.marks)

    def display(self):
        print(f"Student: {self.name} | Roll: {self.roll_no} | Avg: {self.get_average():.2f}")

class Employee(Person):
    def __init__(self, name, age, emp_id, salary, department):
        super().__init__(name, age)
        self.emp_id = emp_id
        self.salary = salary
        self.department = department

    def display(self):
        print(f"Employee: {self.name} | ID: {self.emp_id} | Dept: {self.department} | Salary: {self.salary}")

# Using the system
students = []
employees = []

# Add sample data
s1 = Student("Emma", 20, "S101", {"Math": 85, "Python": 92})
e1 = Employee("Mr. Rao", 35, "E201", 65000, "AI")

students.append(s1)
employees.append(e1)

print("=== MANAGEMENT SYSTEM ===")
print("Students:")
for s in students:
    s.display()

print("\nEmployees:")
for e in employees:
    e.display()

=== MANAGEMENT SYSTEM ===
Students:
Student: Emma | Roll: S101 | Avg: 88.50

Employees:
Employee: Mr. Rao | ID: E201 | Dept: AI | Salary: 65000


In [6]:
#DAY 8: NUMPY ARRAYS- THE FOUNDATION OF ML
import numpy as np

# Creating Arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])   # 2D

print(arr1)
print(arr2)

print("Shape:", arr2.shape)
print("Dimension:", arr2.ndim)
print("Data Type:", arr2.dtype)
print("Size:", arr2.size)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimension: 2
Data Type: int64
Size: 6


In [10]:
# Special Arrays
zeros = np.zeros((3, 4))
ones = np.ones((2, 3))
full = np.full((2, 2), 7)
eye = np.eye(4)                    # Identity matrix
random_arr = np.random.rand(3, 3)  # random 0-1
randint = np.random.randint(1, 100, size=(2, 5))

print(zeros)
print(ones)
print(eye)
print(full)
print(random_arr)
print(randint)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[7 7]
 [7 7]]
[[0.98335969 0.62495052 0.09416297]
 [0.71351559 0.26452195 0.34943528]
 [0.88783979 0.26682396 0.91865379]]
[[42 64 35 11 83]
 [81 94 93 17 93]]


In [8]:
# Arithmetic Operations (Element-wise)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a * b)
print(a ** 2)
print(np.sqrt(a))

[5 7 9]
[ 4 10 18]
[1 4 9]
[1.         1.41421356 1.73205081]


In [11]:
# Indexing & Slicing
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(arr[0, 1])      # 20
print(arr[1, :])      # second row
print(arr[:, 2])      # third column
print(arr[1:3, 0:2])  # subarray

20
[40 50 60]
[30 60 90]
[[40 50]
 [70 80]]


In [12]:
# Useful Functions
arr = np.array([1, 5, 3, 8, 2])

print("Sum:", arr.sum())
print("Mean:", arr.mean())
print("Max:", arr.max())
print("Min:", arr.min())
print("Standard Deviation:", arr.std())

print(np.sort(arr))

Sum: 19
Mean: 3.8
Max: 8
Min: 1
Standard Deviation: 2.481934729198171
[1 2 3 5 8]


In [18]:
#Exercise 1: create a 1d numpy array
arr = np.array([10, 13, 16, 12, 17, 18, 19, 20, 15, 14])

print(arr)

[10 13 16 12 17 18 19 20 15 14]


In [24]:
#Exerciise 2: create 3*3 array of zeroes
zeros = np.zeros((3, 3))
ones = np.ones((2, 4))

print(zeros)
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [26]:
#Exercise 3: create an array and multiply every elemeny by 3
a = np.array([5, 10, 15, 20, 25])

#multiply every element by 3
result_array = a * 3
print(result_array)

[15 30 45 60 75]


In [28]:
#Exercise 4: create a 4x4 matrix

b = np.eye(4)

print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [29]:
#Exercise 5: generate 10 random integers between 50 and 100
random_integers = np.random.randint(50, 101, size=10)

print(random_integers)

[ 55 100  57  74  68  81  65  83  80  69]


In [30]:
#Exercise 6: create two arrays and compute element wise sum, difference, and product
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

#compute element-wise
print(a + b)
print(a - b)
print(a * b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [41]:
#Exercise 7: create a 5x5 array with random values

a = np.random.randint(10, 20, size=(5, 5))

print(a)

#mean
print("Mean:", a.mean())
print("Max:", a.max())
print("Min:", a.min())


[[14 16 10 18 15]
 [15 18 14 19 10]
 [11 11 13 16 17]
 [10 15 12 10 10]
 [12 15 13 11 14]]
Mean: 13.56
Max: 19
Min: 10


In [36]:
#Exercise 8: create a 3x4 array
a = np.array([[1, 2, 3, 4], [2, 11, 30, 14], [17, 22, 28, 13]])

#call only the second row and third column
print(a[1, :])
print(a[:, 2])

[ 2 11 30 14]
[ 3 30 28]


In [50]:
#Exercise 9: create an array of 20 random numbers between 0 and 1
a = np.random.rand(20)

print(a)
#count nhow many numbers greater 0.5
count = 0
for num in a:
  if num > 0.5:
    count += 1
print(count)

[0.61029643 0.98061011 0.77264286 0.2478195  0.64782097 0.35843243
 0.60317165 0.23970686 0.38590858 0.70088647 0.10016277 0.62576974
 0.85390419 0.83999884 0.47469444 0.39624255 0.36478437 0.2816486
 0.79541883 0.7472516 ]
11


In [51]:
#Exercise 10: create a 1D array of 10 numbers

a = np.array([1, 3, 5, 4, 7, 10, 6, 9, 8, 2])

#sort the numbers
print(np.sort(a))

[ 1  2  3  4  5  6  7  8  9 10]


In [53]:
#Exercise 11
import numpy as np

# Create a 4x4 matrix of zeros
a = np.zeros((4, 4), dtype=int)

# Replace all border elements with 99
a[0, :] = 99   # Top row
a[-1, :] = 99  # Bottom row
a[:, 0] = 99   # Left column
a[:, -1] = 99  # Right column

print(a)

[[99 99 99 99]
 [99  0  0 99]
 [99  0  0 99]
 [99 99 99 99]]


In [60]:
#exercise 12;
import numpy as np

#create 2x2 matrices
a = np.random.randint(1, 10, size=(2, 2))
b = np.random.randint(1, 10, size=(2, 2))

#multiplication using @
result = a @ b

print("Matrix A:")
print(a)
print("\nMatrix B:")
print(b)
print("\nResult of A @ B:")
print(result)

Matrix A:
[[4 7]
 [7 4]]

Matrix B:
[[7 7]
 [8 2]]

Result of A @ B:
[[84 42]
 [81 57]]


In [63]:
# Exercise 13: Generate 1000 random numbers in a normal distribution
# np.random.randn generates numbers from a normal distribution (mean=0, std=1)
a = np.random.randn(1000)

# Calculate and print mean and standard deviation
print(f"Mean: {a.mean():.4f}")
print(f"Standard Deviation: {a.std():.4f}")

Mean: -0.0146
Standard Deviation: 1.0008


In [64]:
#Exercise 14:
import numpy as np

# Create a 6x6 array with values from 1 to 36
matrix_6x6 = np.arange(1, 37).reshape(6, 6)
print("6x6 Matrix:")
print(matrix_6x6)

# Extract the main diagonal
main_diagonal = np.diag(matrix_6x6)

print("\nMain Diagonal Elements:")
print(main_diagonal)

6x6 Matrix:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Main Diagonal Elements:
[ 1  8 15 22 29 36]


In [66]:
#Exercise 15
import numpy as np

def array_stats(arr):
    """
    Takes a NumPy array and returns a dictionary with basic statistics.
    """
    return {
        "sum": np.sum(arr),
        "mean": np.mean(arr),
        "max": np.max(arr),
        "min": np.min(arr),
        "shape": arr.shape
    }

# Test the function
test_arr = np.random.rand(3, 4)
stats = array_stats(test_arr)
print("Array Statistics:")
for key, value in stats.items():
    print(f"{key.capitalize()}: {value}")

Array Statistics:
Sum: 6.658806313419069
Mean: 0.5549005261182557
Max: 0.9893960263831999
Min: 0.08366348801134782
Shape: (3, 4)


In [67]:
import numpy as np

def matrix_calculator():
    print("=== NumPy Matrix Calculator ===")

    # Create two matrices
    print("Enter elements for Matrix A (2x2):")
    a = np.array([[int(input()), int(input())],
                  [int(input()), int(input())]])

    print("Enter elements for Matrix B (2x2):")
    b = np.array([[int(input()), int(input())],
                  [int(input()), int(input())]])

    print("\nMatrix A:\n", a)
    print("Matrix B:\n", b)

    print("\n1. Addition\n2. Subtraction\n3. Element-wise Multiplication\n4. Matrix Multiplication\n5. Exit")
    choice = int(input("Choose operation: "))

    if choice == 1:
        print("A + B =\n", a + b)
    elif choice == 2:
        print("A - B =\n", a - b)
    elif choice == 3:
        print("A * B =\n", a * b)
    elif choice == 4:
        print("A @ B =\n", a @ b)
    elif choice == 5:
        print("Goodbye!")
    else:
        print("Invalid choice")

matrix_calculator()

=== NumPy Matrix Calculator ===
Enter elements for Matrix A (2x2):
1
2
4
5
Enter elements for Matrix B (2x2):
4
3
2
5

Matrix A:
 [[1 2]
 [4 5]]
Matrix B:
 [[4 3]
 [2 5]]

1. Addition
2. Subtraction
3. Element-wise Multiplication
4. Matrix Multiplication
5. Exit
Choose operation: 1
A + B =
 [[ 5  5]
 [ 6 10]]
